# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# Actually hourly, but such workflows are commonly named "daily" 
name: Daily

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  maintenance:
    uses: ./.github/workflows/daily.yml
    permissions:
      contents: write
      issues: write
      pull-requests: write
      pages: write
      id-token: write
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout config file
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run renovate
        uses: renovatebot/github-action@316d7cd859606d6039a2182b7d69199e9b036835 # v46.2.1
        with:
          token: ${{ secrets.SCORE_BOT_CLASSIC_PAT }}
          configurationFile: .github/renovate.json5
        env:
          LOG_LEVEL: debug
