# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Documentation Verification

on:
  workflow_call:
    inputs:
      bazel-docs-verify-target:
        description: "Bazel target for docs verification"
        required: false
        type: string
        default: "//:docs_check"
    outputs:
      verification-result:
        description: "Result of the docs verification"
        value: ${{ jobs.docs-verify.outputs.verification-result }}

env:
  CACHE_KEY_PREFIX: bazel-cache

jobs:
  docs-verify:
    name: Docs Verification
    runs-on: ${{ vars.runner_labels_ghub_standard_x64 && fromJSON(vars.runner_labels_ghub_standard_x64) || vars.REPO_RUNNER_LABELS && fromJSON(vars.REPO_RUNNER_LABELS) || 'ubuntu-latest' }}
    outputs:
      verification-result: ${{ steps.verify.outcome }}
    permissions:
      contents: read
    steps:
      - uses: eclipse-score/more-disk-space@3fac5780033e636b114cf69e891dc19d640855c2 # v1.1
        with:
          level: 3

      - name: Checkout repository (Handle all events)
        uses: actions/checkout@v7
        with:
          lfs: true
          ref: ${{ github.head_ref || github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: Setup Bazel
        uses: eclipse-score/cicd-actions/setup-bazel-cache@212bbf86267e9381da9d2daf962d12f6feafbc90
        with:
          unique-cache-name: ${{ github.job }}

      - name: Install Graphviz
        uses: eclipse-score/apt-install@main
        with:
          packages: graphviz
          cache: false

      - name: Run docs verification
        id: verify
        run: |
          bazel run ${{ inputs.bazel-docs-verify-target }}
