# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Tests

on:
  workflow_call:
    inputs:
      bazel-target:
        description: "Custom Bazel target to run (e.g.: 'test //src/...')"
        required: false
        default: "test //..."
        type: string
      upload-name:
        description: "Custom name to upload test results to (e.g. Bazel Test Results). Leave as default to skip upload."
        required: false
        default: "NO UPLOAD OF TEST RESULTS CONFIGURED"
        type: string
      result-paths:
        description: "Custom paths to upload test results from (e.g.: 'bazel-testlogs/**/*.xml')"
        required: false
        default: |
          bazel-testlogs/**/*.xml
          bazel-testlogs/**/test.log
        type: string
      packages:
        description: "Custom packages to install before running tests"
        required: false
        default: ""
        type: string

jobs:
  unit-tests:
    name: Test Execution
    runs-on: ${{ vars.runner_labels_ghub_standard_x64 && fromJSON(vars.runner_labels_ghub_standard_x64) || vars.REPO_RUNNER_LABELS && fromJSON(vars.REPO_RUNNER_LABELS) || 'ubuntu-latest' }}

    steps:
      - uses: eclipse-score/more-disk-space@3fac5780033e636b114cf69e891dc19d640855c2 # v1.1

      - name: Checkout repository (Handle all events)
        uses: actions/checkout@v7
        with:
          lfs: true
          ref: ${{ github.head_ref || github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: Install dependencies
        if: ${{ inputs.packages != '' }}
        uses: eclipse-score/apt-install@main
        with:
          packages: ${{ inputs.packages }}
          cache: false

      - name: Setup Bazel with shared caching
        uses: eclipse-score/cicd-actions/setup-bazel-cache@212bbf86267e9381da9d2daf962d12f6feafbc90
        with:
          unique-cache-name: ${{ github.job }}

      - name: Run Tests via Bazel
        run: |
          set -euo pipefail
          echo "Running: bazel ${{ inputs.bazel-target }}"
          bazel ${{ inputs.bazel-target }}

      - name: Upload Bazel test artifacts
        if: ${{ always() && inputs.upload-name != 'NO UPLOAD OF TEST RESULTS CONFIGURED' }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.upload-name }}
          path: |
            ${{ inputs.result-paths }}
          if-no-files-found: warn
          compression-level: 6
